version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: francescoxx/nestapp:1.0.0
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - mongodb
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MONGO_INITDB_DATABASE=vila
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password


  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/database/01_reference_data.sql:/docker-entrypoint-initdb.d/01_reference_data.sql
      - ./src/database/02_hero_attribute.sql:/docker-entrypoint-initdb.d/02_hero_attribute.sql
      - ./src/database/03_hero_power.sql:/docker-entrypoint-initdb.d/03_hero_power.sql

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      MONGO_INITDB_DATABASE: vila

volumes:
  pgdata:

